# Generated by Django 4.1.3 on 2023-03-29 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('extimated_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(message='Hours must be between 0 to 90999 digits.', regex='^\\d{0,90999}$')])),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(message='Hours must be between 0 to 90999 digits.', regex='^\\d{0,90999}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
