# Generated by Django 4.1.3 on 2023-03-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projement_app', '0003_project_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='extimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
